test release 4

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,7 +28,21 @@ jobs:
       - name: Get application list
         id: get_applications
         run: |
-          echo "dirs=$(find ./cmd -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)" >> $GITHUB_OUTPUT
+          # Проверяем существование папки ./cmd/
+          if [ ! -d "./cmd" ]; then
+            echo "Error: Directory ./cmd does not exist."
+            exit 1
+          fi
+
+          # Используем find для получения только директорий в ./cmd/
+          dirs=$(find ./cmd -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
+          if [ -z "$dirs" ]; then
+            echo "Error: No directories found in ./cmd/"
+            exit 1
+          fi
+
+          # Записываем результат в переменную окружения
+          echo "dirs=$dirs" >> $GITHUB_OUTPUT
 
       # Проверяем, что список директорий не пустой
       - name: Check if applications exist
